class EndPoints {
  EndPoints._();
  static const String signUpPath = "signup";
  static const String signInPath = "signin";
  static const String otp = "otp-check";
  static const String register = "store";
  static const String resendOtp = "otp-resend";
  static const String signUp = "signup";
  static const String home = "home";
  static const String allCategory = "all-category";
  static const String categoryProduct = "category-products";
  static const String product = "product-view";
  static const String subscription = "subscription-create";
  static const String addToCart = "add-to-cart";
  static const String productVariants = "product-variants";
  static const String removeCartItem = "remove-cart-item";
  static const String updateCartItemQty = "cart-update";
  static const String placeOrder = "order-place";
  static const String orders = "orders";
  static const String cancelOrder = "order-cancel";
  static const String mySubscription = "my-subscription";
  static const String temporaryChange = "temporary-change";
  static const String pauseSubscription = "pause-subscription";
  static const String resumeSubscription = "resume-subscription";
  static const String permanentChangeSubscription = "update-quantity";
  static const String deleteSubscription = "delete-subscription";
  static const String rechargeHistory = "wallet-history";
  static const String billingHistory = "billing-history";
  static const String payCash = "payment-request";
  static const String payOnline = "pay-online";
  static const String verifyPayment = "verify-payment";
  static const String allProduct = "category-products";
  static const String wallet = "wallet";
  static const String profile = "profile";
  static const String vacation = "vacation-update";
  static const String getAreas = "{id}";
}
