import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class AppIcons {
  AppIcons._();

  static const IconData mobile = Icons.mobile_friendly;
  static const IconData backArrow = Icons.arrow_back;
  static const IconData user = Icons.perm_identity_outlined;
  static const IconData successIcons = Icons.check_circle;
  static const IconData errorIcons = Icons.error;
  static const IconData menuIcons = Icons.menu;
  static const IconData walletIcons = Icons.wallet;
  static const IconData person = Icons.person;
  static const IconData preference = Icons.checklist;
  static const IconData cart = Icons.shopping_cart_sharp;
  static const IconData order = Icons.bookmark_border;
  static const IconData subscriptions = Icons.subscriptions;
  static const IconData invoice = Icons.picture_as_pdf;
  static const IconData help = Icons.help;
  static const IconData notification = Icons.notifications_rounded;
  static const IconData verified = Icons.verified_rounded;
  static const IconData copy = Icons.copy;
  static const IconData wallet = Icons.wallet;
  static const IconData credit = Icons.credit_card;
  static const IconData add = Icons.add;
  static const IconData remove = Icons.remove;
  static const IconData arrowDropDown = Icons.arrow_drop_down;
  static const IconData close = Icons.close;
  static const IconData location = Icons.location_on;
  static const IconData bike = Icons.pedal_bike_outlined;
  static const IconData delete = CupertinoIcons.trash;
  static const IconData cancelRounded = Icons.cancel_rounded;
  static const IconData productIcons = Icons.grid_view;
  static const IconData home = Icons.home;
  static const IconData calendar = Icons.calendar_month;
  static const IconData pause = Icons.pause;
  static const IconData resume = Icons.play_arrow;
  static const IconData restore = Icons.restore;
  static const IconData wallet2 = Icons.account_balance_wallet_outlined;
  static const IconData currencyRupee = Icons.currency_rupee;
  static const IconData email = Icons.mail;
  static const IconData forwardArrow = Icons.arrow_forward;
  static const IconData pageBackArrow = Icons.arrow_back_ios_new_sharp;
  static const IconData editIcon = Icons.edit;
  static const IconData refresh = Icons.refresh;
  static const IconData referEarn = CupertinoIcons.person_2;
  static const IconData orderCube = CupertinoIcons.cube;
  static const IconData billingHistory = CupertinoIcons.book_fill;
}
